services:
  - type: web
    name: forum-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn forum.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: forum.settings
      - key: DATABASE_URL
        fromDatabase:
          name: forum-db
          property: connectionString

databases:
  - name: forum-db
    databaseName: forumdb
    user: forumuser
