services:
  - type: web
    name: forum-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn forum.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: forum.settings
      - key: SECRET_KEY
        value: django-insecure-6d7^wwqbt(kcmm*a9mhox2_l$cwg7a*x$j^_a0ydc(e=)6dbbg
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: forum-app-frrc.onrender.com


