# Generated by Django 5.2.2 on 2025-06-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='votecount',
            field=models.IntegerField(default=0),
        ),
    ]
