# Generated by Django 5.2.2 on 2025-06-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_votecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='votecount',
            new_name='vote_count',
        ),
    ]
