# Generated by Django 5.2.3 on 2025-06-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_rename_votecount_topic_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
