# Generated by Django 5.2.3 on 2025-06-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(unique=True)),
                ('unique_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
